// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjcwsIgRJl-fVLomJyEccfa2TfWpvCEo',
    appId: '1:786765336174:web:af7bf46bf99cf36747607f',
    messagingSenderId: '786765336174',
    projectId: 'wallet-go-4e13a',
    authDomain: 'wallet-go-4e13a.firebaseapp.com',
    storageBucket: 'wallet-go-4e13a.firebasestorage.app',
    measurementId: 'G-5F79N44JRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39GagcGIYFbN2TTOBa05ekC_xZ7SdCtI',
    appId: '1:786765336174:android:dfc19324f0db6fff47607f',
    messagingSenderId: '786765336174',
    projectId: 'wallet-go-4e13a',
    storageBucket: 'wallet-go-4e13a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-WBpTu1YQ8yo-hi0kuuEei3BZC47XTog',
    appId: '1:786765336174:ios:97211a4cde68cf7147607f',
    messagingSenderId: '786765336174',
    projectId: 'wallet-go-4e13a',
    storageBucket: 'wallet-go-4e13a.firebasestorage.app',
    iosBundleId: 'com.example.walletGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-WBpTu1YQ8yo-hi0kuuEei3BZC47XTog',
    appId: '1:786765336174:ios:97211a4cde68cf7147607f',
    messagingSenderId: '786765336174',
    projectId: 'wallet-go-4e13a',
    storageBucket: 'wallet-go-4e13a.firebasestorage.app',
    iosBundleId: 'com.example.walletGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjcwsIgRJl-fVLomJyEccfa2TfWpvCEo',
    appId: '1:786765336174:web:b103ca736bc2c88d47607f',
    messagingSenderId: '786765336174',
    projectId: 'wallet-go-4e13a',
    authDomain: 'wallet-go-4e13a.firebaseapp.com',
    storageBucket: 'wallet-go-4e13a.firebasestorage.app',
    measurementId: 'G-1JVM77B1SF',
  );
}
